build site:
  image: node:20
  stage: build
  script:
    - npm install --progress=false
    - npm run build
    
  artifacts:
    expire_in: 1 week
    paths:
      - dist

variables:
  FTP_USERNAME: "cams_stage"
  FTP_PASSWORD: "esh@len$$1"
  FTP_HOST: "103.195.4.8"

deploy:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y lftp
    - lftp -e "set ssl:verify-certificate false; mirror -R ./dist ./apitest" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
  only:
    - new_backend
